# ----------
# SPDX-License-Identifier: Apache-2.0
# ----------
#
version: '3.5'

networks:
  tlsring.net:
    name: tlsring.blockchain

services:
  tlsring.rca:
    container_name: tlsring.rca
    image: hyperledger/fabric-ca:1.4.9
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=tlsring.blockchain
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca/server
      - FABRIC_CA_SERVER_PORT=5005
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_NAME=rca.tlsring.blockchain.biz
      - FABRIC_CA_SERVER_CSR_CN=tlsring.blockchain.biz
      - FABRIC_CA_SERVER_CSR_HOSTS=rca.tlsring.blockchain.biz
      - FABRIC_CA_SERVER_DEBUG=true
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:5045
      - FABRIC_CA_SERVER_METRICS_PROVIDER=prometheus
    working_dir: /etc/hyperledger/fabric-ca/server 
    volumes:
      # VM docker stream folder mapping
      - /var/run/:/host/var/run/
      # Map the folder to root of Fabric CA crypto assets
      - ./rca:/etc/hyperledger/fabric-ca
    networks:
      - tlsring.net
    ports:
      - 5005:5005
      - 5045:5045
    command: sh -c 'fabric-ca-server start -d -b tlsr-admin:tlsr-pwd --port 5005'
