# ----------
# SPDX-License-Identifier: Apache-2.0
# ----------
#
version: '3.5'

networks:
  coffee.net:
    name: coffee.blockchain

services:

  coffee.rca:
    container_name: coffee.rca
    image: hyperledger/fabric-ca:1.4.9
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=coffee.blockchain
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca/server
      - FABRIC_CA_SERVER_PORT=7005
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_NAME=rca.coffee.blockchain.biz
      - FABRIC_CA_SERVER_CSR_CN=coffee.blockchain.biz
      - FABRIC_CA_SERVER_CSR_HOSTS=rca.coffee.blockchain.biz
      - FABRIC_CA_SERVER_DEBUG=true
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:7045
      - FABRIC_CA_SERVER_METRICS_PROVIDER=prometheus
    working_dir: /etc/hyperledger/fabric-ca/server 
    volumes:
      # VM docker stream folder mapping
      - /var/run/:/host/var/run/
      # Map the folder to root of Fabric CA crypto assets
      - ./rca:/etc/hyperledger/fabric-ca
    ports:
      - 7005:7005
      - 7045:7045
    networks:
      - coffee.net
    command: sh -c 'fabric-ca-server start -d -b rca-admin:rca-pwd --port 7005'

# ==================================================================

  coffee.peer0.couchdb:
    container_name: coffee.peer0.couchdb
    image: hyperledger/fabric-couchdb:0.4.22
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=coffee.blockchain
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_PEER_NETWORKID=coffee.net
      - COUCHDB_USER=admin-db
      - COUCHDB_PASSWORD=admin-pwd
    working_dir: /etc/hyperledger/couchdb
    volumes:
      # VM docker stream folder mapping
      - /var/run/:/host/var/run/
      # Default root path
      - ./couchdb0:/etc/hyperledger/couchdb
    ports:
      # internal port changed to avoid conflict with other peer in other docker-compose.yml
      - 7132:5984
    networks:
      - coffee.net

  coffee.peer0:
    container_name: coffee.peer0
    image: hyperledger/fabric-peer:1.4.9
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=coffee.blockchain
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - CORE_PEER_FILESYSTEMPATH=/etc/hyperledger/fabric/ledger
      - CORE_PEER_NETWORKID=coffee.net
      - CORE_PEER_ADDRESSAUTODETECT=false
      - CORE_PEER_ID=peer0.coffee.blockchain.biz
      - CORE_PEER_LOCALMSPID=CoffeeMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/peer0/msp
      - CORE_PEER_ADDRESS=peer0.coffee.blockchain.biz:7134
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7134
      - CORE_PEER_ADMINSERVICE_LISTENADDRESS=0.0.0.0:7134
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7135
      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:7136
      # Go profiling tools only in none production environment
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_COMMITTER_ENABLED=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/msp/users/peer0/tls-msp/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/msp/users/peer0/tls-msp/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/users/peer0/tls-msp/tlscacerts/tls-rca-tlsring-blockchain-biz-5005.pem
      # - CORE_PEER_CHAINCODE_MODE=dev
      # - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.coffee.blockchain.biz:7134
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.coffee.blockchain.biz:7134
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.coffee.blockchain.biz:7134
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      # Logging
      - FABRIC_LOGGING_SPEC=info:ledger,peer,couchdb=info
      # - CORE_LOGGING_LEVEL=info:ledger,peer,couchdb=info
      # - CORE_LOGGING_COUCHDB=info
      # - CORE_LOGGING_CAUTHDSL=info
      # - CORE_LOGGING_GOSSIP=info
      # - CORE_LOGGING_GRPC=info
      # - CORE_LOGGING_KVLEDGER=info
      # - CORE_LOGGING_LEDGER=info
      # - CORE_LOGGING_MSP=info
      # - CORE_LOGGING_PEER=info
      # - CORE_LOGGING_POLICIES=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_CHAINCODE_LOGGING_SHIM=info
      - GRPC_GO_LOG_VERBOSITY_LEVEL=99
      - GRPC_GO_LOG_SEVERITY_LEVEL=info
      # Operations
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:7145
      - CORE_METRICS_PROVIDER=prometheus
      # For each historic key update, the historic value and associated transaction id and timestamp 
      # are stored in history database. See Class: ChaincodeStub and method <async> getHistoryForKey(key)
      - CORE_LEDGER_HISTORY_ENABLEHISTORYDATABASE=true
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=coffee.peer0.couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin-db
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=admin-pwd
      # Additional PEER vars to support configs at runtime
      - TLSR_TLS_CERT=/etc/hyperledger/msp/client/tls-ca/rca-tlsring-tls-cert.pem
      - RCA_TLS_CERT=/etc/hyperledger/msp/client/tls-ca/rca-coffee-tls-cert.pem
      - PEER_CACERT=/etc/hyperledger/msp/users/peer0/msp/cacerts/rca-coffee-blockchain-biz-7005.pem
      - ADMIN_SIGNCERTS=/etc/hyperledger/msp/users/admin/msp/signcerts/cert.pem
    working_dir: /etc/hyperledger/fabric
    volumes:
      # VM docker stream folder mapping
      - /var/run/:/host/var/run/
      # Default root path
      - ./peer0:/etc/hyperledger/fabric
      # Map the folder to root of Fabric CA crypto assets
      - ./rca:/etc/hyperledger/msp/
      # Folder with block channel config and tx file
      - ../config:/etc/hyperledger/config
      - ../channel:/etc/hyperledger/channel
      # For chaincode and application
      - ../application:/etc/hyperledger/application
      - ../chaincode:/etc/hyperledger/chaincode
    ports:
      - 7134:7134
      - 7135:7135
      - 7136:7136
      - 7145:7145
    networks:
      - coffee.net
    depends_on:
      - coffee.peer0.couchdb
    command: peer node start
    # command: peer node start --peer-chaincodedev=true

  coffee.peer0.cli:
    container_name: coffee.peer0.cli
    image: hyperledger/fabric-tools:2.3.2
    tty: true
    stdin_open: true
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=coffee.blockchain
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - CORE_PEER_FILESYSTEMPATH=/etc/hyperledger/fabric/ledger
      - FABRIC_LOGGING_SPEC=info
      - CORE_PEER_NETWORKID=coffee.net
      - CORE_PEER_ADDRESSAUTODETECT=false
      - CORE_PEER_ID=peer0.coffee.blockchain.biz
      - CORE_PEER_LOCALMSPID=CoffeeMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/admin/msp
      - CORE_PEER_ADDRESS=peer0.coffee.blockchain.biz:7134
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/msp/users/peer0/tls-msp/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/msp/users/peer0/tls-msp/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/users/peer0/tls-msp/tlscacerts/tls-rca-tlsring-blockchain-biz-5005.pem
      # Logging
      - FABRIC_LOGGING_SPEC=debug:ledger,peer,couchdb=debug
      # - CORE_LOGGING_LEVEL=info:ledger,peer,couchdb=info
      # - CORE_LOGGING_COUCHDB=info
      # - CORE_LOGGING_CAUTHDSL=info
      # - CORE_LOGGING_GOSSIP=info
      # - CORE_LOGGING_GRPC=info
      # - CORE_LOGGING_KVLEDGER=info
      # - CORE_LOGGING_LEDGER=info
      # - CORE_LOGGING_MSP=info
      # - CORE_LOGGING_PEER=info
      # - CORE_LOGGING_POLICIES=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_CHAINCODE_LOGGING_SHIM=info
      - GRPC_GO_LOG_VERBOSITY_LEVEL=99
      - GRPC_GO_LOG_SEVERITY_LEVEL=info
      # Additional PEER vars to support configs at runtime
      - TLSR_TLS_CERT=/etc/hyperledger/msp/client/tls-ca/rca-tlsring-tls-cert.pem
      - RCA_TLS_CERT=/etc/hyperledger/msp/client/tls-ca/rca-coffee-tls-cert.pem
      - PEER_CACERT=/etc/hyperledger/msp/users/peer0/msp/cacerts/rca-coffee-blockchain-biz-7005.pem
      - ADMIN_SIGNCERTS=/etc/hyperledger/msp/users/admin/msp/signcerts/cert.pem
    working_dir: /etc/hyperledger/fabric
    volumes:
      # VM docker stream folder mapping
      - /var/run/:/host/var/run/
      # Default root path
      - ./peer0:/etc/hyperledger/fabric
      # Map the folder to root of Fabric CA crypto assets
      - ./rca:/etc/hyperledger/msp/
      # Folder with block channel config and tx file
      - ../config:/etc/hyperledger/config
      - ../channel:/etc/hyperledger/channel
      # For chaincode and application
      - ../application:/etc/hyperledger/application
      - ../chaincode:/etc/hyperledger/chaincode
    networks:
      - coffee.net
    depends_on:
      - coffee.peer0
    command: /bin/bash

# ==================================================================

  coffee.peer1.couchdb:
    container_name: coffee.peer1.couchdb
    image: hyperledger/fabric-couchdb:0.4.22
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admicouchdb1n Party" mode.
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=coffee.blockchain
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_PEER_NETWORKID=coffee.net
      - COUCHDB_USER=admin-db
      - COUCHDB_PASSWORD=admin-pwd
    working_dir: /etc/hyperledger/couchdb
    volumes:
      # VM docker stream folder mapping
      - /var/run:/host/var/run
      # Default root path
      - ./couchdb1:/etc/hyperledger/couchdb
    ports:
      # internal port changed to avoid conflict with other peer in other docker-compose.yml
      - 7232:5984
    networks:
      - coffee.net

  coffee.peer1:
    container_name: coffee.peer1
    image: hyperledger/fabric-peer:1.4.9
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=coffee.blockchain
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - CORE_PEER_FILESYSTEMPATH=/etc/hyperledger/fabric/ledger
      - CORE_PEER_NETWORKID=coffee.net
      - CORE_PEER_ADDRESSAUTODETECT=false
      - CORE_PEER_ID=peer1.coffee.blockchain.biz
      - CORE_PEER_LOCALMSPID=CoffeeMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/peer1/msp
      - CORE_PEER_ADDRESS=peer1.coffee.blockchain.biz:7234
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7234
      - CORE_PEER_ADMINSERVICE_LISTENADDRESS=0.0.0.0:7234
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7235
      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:7236
      # Go profiling tools only in none production environment
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_COMMITTER_ENABLED=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/msp/users/peer1/tls-msp/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/msp/users/peer1/tls-msp/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/users/peer1/tls-msp/tlscacerts/tls-rca-tlsring-blockchain-biz-5005.pem
      # - CORE_PEER_CHAINCODE_MODE=dev
      # - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.coffee.blockchain.biz:7234
      - CORE_PEER_GOSSIP_ENDPOINT=peer1.coffee.blockchain.biz:7234
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.coffee.blockchain.biz:7234
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      # Logging
      - FABRIC_LOGGING_SPEC=info:ledger,peer,couchdb=info
      # - CORE_LOGGING_LEVEL=info:ledger,peer,couchdb=info
      # - CORE_LOGGING_COUCHDB=info
      # - CORE_LOGGING_CAUTHDSL=info
      # - CORE_LOGGING_GOSSIP=info
      # - CORE_LOGGING_GRPC=info
      # - CORE_LOGGING_KVLEDGER=info
      # - CORE_LOGGING_LEDGER=info
      # - CORE_LOGGING_MSP=info
      # - CORE_LOGGING_PEER=info
      # - CORE_LOGGING_POLICIES=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_CHAINCODE_LOGGING_SHIM=info
      - GRPC_GO_LOG_VERBOSITY_LEVEL=99
      - GRPC_GO_LOG_SEVERITY_LEVEL=info
      # Operations
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:7245
      - CORE_METRICS_PROVIDER=prometheus
      # For each historic key update, the historic value and associated transaction id and timestamp 
      # are stored in history database. See Class: ChaincodeStub and method <async> getHistoryForKey(key)
      - CORE_LEDGER_HISTORY_ENABLEHISTORYDATABASE=true
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=coffee.peer1.couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin-db
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=admin-pwd
      # Additional PEER vars to support configs at runtime
      - TLSR_TLS_CERT=/etc/hyperledger/msp/client/tls-ca/rca-tlsring-tls-cert.pem
      - RCA_TLS_CERT=/etc/hyperledger/msp/client/tls-ca/rca-coffee-tls-cert.pem
      - PEER_CACERT=/etc/hyperledger/msp/users/peer1/msp/cacerts/rca-coffee-blockchain-biz-7005.pem
      - ADMIN_SIGNCERTS=/etc/hyperledger/msp/users/admin/msp/signcerts/cert.pem
    working_dir: /etc/hyperledger/fabric
    volumes:
      # VM docker stream folder mapping
      - /var/run/:/host/var/run/
      # Default root path
      - ./peer1:/etc/hyperledger/fabric
      # Map the folder to root of Fabric CA crypto assets
      - ./rca:/etc/hyperledger/msp/
      # Folder with block channel config and tx file
      - ../config:/etc/hyperledger/config
      - ../channel:/etc/hyperledger/channel
      # For chaincode and application
      - ../application:/etc/hyperledger/application
      - ../chaincode:/etc/hyperledger/chaincode
    ports:
      - 7234:7234
      - 7235:7235
      - 7236:7236
      - 7245:7245
    networks:
      - coffee.net
    depends_on:
      - coffee.peer1.couchdb
    command: peer node start
    # command: peer node start --peer-chaincodedev=true

  coffee.peer1.cli:
    container_name: coffee.peer1.cli
    image: hyperledger/fabric-tools:2.3.2
    tty: true
    stdin_open: true
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=coffee.blockchain
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - CORE_PEER_FILESYSTEMPATH=/etc/hyperledger/fabric/ledger
      - FABRIC_LOGGING_SPEC=info
      - CORE_PEER_NETWORKID=coffee.net
      - CORE_PEER_ADDRESSAUTODETECT=false
      - CORE_PEER_ID=peer1.coffee.blockchain.biz
      - CORE_PEER_LOCALMSPID=CoffeeMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/admin/msp
      - CORE_PEER_ADDRESS=peer1.coffee.blockchain.biz:7234
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/msp/users/peer1/tls-msp/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/msp/users/peer1/tls-msp/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/users/peer1/tls-msp/tlscacerts/tls-rca-tlsring-blockchain-biz-5005.pem
      # Logging
      - FABRIC_LOGGING_SPEC=debug:ledger,peer,couchdb=debug
      # - CORE_LOGGING_LEVEL=info:ledger,peer,couchdb=info
      # - CORE_LOGGING_COUCHDB=info
      # - CORE_LOGGING_CAUTHDSL=info
      # - CORE_LOGGING_GOSSIP=info
      # - CORE_LOGGING_GRPC=info
      # - CORE_LOGGING_KVLEDGER=info
      # - CORE_LOGGING_LEDGER=info
      # - CORE_LOGGING_MSP=info
      # - CORE_LOGGING_PEER=info
      # - CORE_LOGGING_POLICIES=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_CHAINCODE_LOGGING_SHIM=info
      - GRPC_GO_LOG_VERBOSITY_LEVEL=99
      - GRPC_GO_LOG_SEVERITY_LEVEL=info
      # Additional PEER vars to support configs at runtime
      - TLSR_TLS_CERT=/etc/hyperledger/msp/client/tls-ca/rca-tlsring-tls-cert.pem
      - RCA_TLS_CERT=/etc/hyperledger/msp/client/tls-ca/rca-coffee-tls-cert.pem
      - PEER_CACERT=/etc/hyperledger/msp/users/peer1/msp/cacerts/rca-coffee-blockchain-biz-7005.pem
      - ADMIN_SIGNCERTS=/etc/hyperledger/msp/users/admin/msp/signcerts/cert.pem
    working_dir: /etc/hyperledger/fabric
    volumes:
      # VM docker stream folder mapping
      - /var/run/:/host/var/run/
      # Default root path
      - ./peer1:/etc/hyperledger/fabric
      # Map the folder to root of Fabric CA crypto assets
      - ./rca:/etc/hyperledger/msp/
      # Folder with block channel config and tx file
      - ../config:/etc/hyperledger/config
      - ../channel:/etc/hyperledger/channel
      # For chaincode and application
      - ../application:/etc/hyperledger/application
      - ../chaincode:/etc/hyperledger/chaincode
    networks:
      - coffee.net
    depends_on:
      - coffee.peer1
    command: /bin/bash

# ==================================================================
