# ----------
# SPDX-License-Identifier: Apache-2.0
# ----------
#
version: '3.5'

networks:
  juice.net:
    name: juice.blockchain

services:

  juice.rca:
    container_name: juice.rca
    image: hyperledger/fabric-ca:1.4.9
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=juice.blockchain
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca/server
      - FABRIC_CA_SERVER_PORT=8005
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_NAME=rca.juice.blockchain.biz
      - FABRIC_CA_SERVER_CSR_CN=juice.blockchain.biz
      - FABRIC_CA_SERVER_CSR_HOSTS=rca.juice.blockchain.biz
      - FABRIC_CA_SERVER_DEBUG=true
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:8045
      - FABRIC_CA_SERVER_METRICS_PROVIDER=prometheus
    working_dir: /etc/hyperledger/fabric-ca/server 
    volumes:
      # VM docker stream folder mapping
      - /var/run/:/host/var/run/
      # Map the folder to root of Fabric CA crypto assets
      - ./rca:/etc/hyperledger/fabric-ca
    ports:
      - 8005:8005
      - 8045:8045
    networks:
      - juice.net
    command: sh -c 'fabric-ca-server start -d -b rca-admin:rca-pwd --port 8005'

# ==================================================================

  juice.peer0.couchdb:
    container_name: juice.peer0.couchdb
    image: hyperledger/fabric-couchdb:0.4.22
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=juice.blockchain
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_PEER_NETWORKID=juice.net
      - COUCHDB_USER=admin-db
      - COUCHDB_PASSWORD=admin-pwd
    working_dir: /etc/hyperledger/couchdb
    volumes:
      # VM docker stream folder mapping
      - /var/run/:/host/var/run/
      # Default root path
      - ./couchdb0:/etc/hyperledger/couchdb
    ports:
      # internal port changed to avoid conflict with other peer in other docker-compose.yml
      - 8132:5984
    networks:
      - juice.net

  juice.peer0:
    container_name: juice.peer0
    image: hyperledger/fabric-peer:1.4.9
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=juice.blockchain
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - CORE_PEER_FILESYSTEMPATH=/etc/hyperledger/fabric/ledger
      - CORE_PEER_NETWORKID=juice.net
      - CORE_PEER_ADDRESSAUTODETECT=false
      - CORE_PEER_ID=peer0.juice.blockchain.biz
      - CORE_PEER_LOCALMSPID=JuiceMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/peer0/msp
      - CORE_PEER_ADDRESS=peer0.juice.blockchain.biz:8134
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8134
      - CORE_PEER_ADMINSERVICE_LISTENADDRESS=0.0.0.0:8134
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8135
      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:8136
      # Go profiling tools only in none production environment
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_COMMITTER_ENABLED=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/msp/users/peer0/tls-msp/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/msp/users/peer0/tls-msp/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/users/peer0/tls-msp/tlscacerts/tls-rca-tlsring-blockchain-biz-5005.pem
      # - CORE_PEER_CHAINCODE_MODE=dev
      # - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.juice.blockchain.biz:8134
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.juice.blockchain.biz:8134
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.juice.blockchain.biz:8134
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      # Logging
      - FABRIC_LOGGING_SPEC=info:ledger,peer,couchdb=info
      # - CORE_LOGGING_LEVEL=info:ledger,peer,couchdb=info
      # - CORE_LOGGING_COUCHDB=info
      # - CORE_LOGGING_CAUTHDSL=info
      # - CORE_LOGGING_GOSSIP=info
      # - CORE_LOGGING_GRPC=info
      # - CORE_LOGGING_KVLEDGER=info
      # - CORE_LOGGING_LEDGER=info
      # - CORE_LOGGING_MSP=info
      # - CORE_LOGGING_PEER=info
      # - CORE_LOGGING_POLICIES=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_CHAINCODE_LOGGING_SHIM=info
      - GRPC_GO_LOG_VERBOSITY_LEVEL=99
      - GRPC_GO_LOG_SEVERITY_LEVEL=info
      # Operations
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:8145
      - CORE_METRICS_PROVIDER=prometheus
      # For each historic key update, the historic value and associated transaction id and timestamp 
      # are stored in history database. See Class: ChaincodeStub and method <async> getHistoryForKey(key)
      - CORE_LEDGER_HISTORY_ENABLEHISTORYDATABASE=true
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=juice.peer0.couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin-db
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=admin-pwd
      # Additional PEER vars to support configs at runtime
      - TLSR_TLS_CERT=/etc/hyperledger/msp/client/tls-ca/rca-tlsring-tls-cert.pem
      - RCA_TLS_CERT=/etc/hyperledger/msp/client/tls-ca/rca-juice-tls-cert.pem
      - PEER_CACERT=/etc/hyperledger/msp/users/peer0/msp/cacerts/rca-juice-blockchain-biz-8005.pem
      - ADMIN_SIGNCERTS=/etc/hyperledger/msp/users/admin/msp/signcerts/cert.pem
    working_dir: /etc/hyperledger/fabric
    volumes:
      # VM docker stream folder mapping
      - /var/run/:/host/var/run/
      # Default root path
      - ./peer0:/etc/hyperledger/fabric
      # Map the folder to root of Fabric CA crypto assets
      - ./rca:/etc/hyperledger/msp/
      # Folder with block channel config and tx file
      - ../config:/etc/hyperledger/config
      - ../channel:/etc/hyperledger/channel
      # For chaincode and application
      - ../application:/etc/hyperledger/application
      - ../chaincode:/etc/hyperledger/chaincode
    ports:
      - 8134:8134
      - 8135:8135
      - 8136:8136
      - 8145:8145
    networks:
      - juice.net
    depends_on:
      - juice.peer0.couchdb
    command: peer node start
    # command: peer node start --peer-chaincodedev=true

  juice.peer0.cli:
    container_name: juice.peer0.cli
    image: hyperledger/fabric-tools:2.3.2
    tty: true
    stdin_open: true
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=juice.blockchain
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - CORE_PEER_FILESYSTEMPATH=/etc/hyperledger/fabric/ledger
      - FABRIC_LOGGING_SPEC=info
      - CORE_PEER_NETWORKID=juice.net
      - CORE_PEER_ADDRESSAUTODETECT=false
      - CORE_PEER_ID=peer0.juice.blockchain.biz
      - CORE_PEER_LOCALMSPID=JuiceMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/admin/msp
      - CORE_PEER_ADDRESS=peer0.juice.blockchain.biz:8134
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/msp/users/peer0/tls-msp/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/msp/users/peer0/tls-msp/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/users/peer0/tls-msp/tlscacerts/tls-rca-tlsring-blockchain-biz-5005.pem
      # Logging
      - FABRIC_LOGGING_SPEC=debug:ledger,peer,couchdb=debug
      # - CORE_LOGGING_LEVEL=info:ledger,peer,couchdb=info
      # - CORE_LOGGING_COUCHDB=info
      # - CORE_LOGGING_CAUTHDSL=info
      # - CORE_LOGGING_GOSSIP=info
      # - CORE_LOGGING_GRPC=info
      # - CORE_LOGGING_KVLEDGER=info
      # - CORE_LOGGING_LEDGER=info
      # - CORE_LOGGING_MSP=info
      # - CORE_LOGGING_PEER=info
      # - CORE_LOGGING_POLICIES=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_CHAINCODE_LOGGING_SHIM=info
      - GRPC_GO_LOG_VERBOSITY_LEVEL=99
      - GRPC_GO_LOG_SEVERITY_LEVEL=info
      # Additional PEER vars to support configs at runtime
      - TLSR_TLS_CERT=/etc/hyperledger/msp/client/tls-ca/rca-tlsring-tls-cert.pem
      - RCA_TLS_CERT=/etc/hyperledger/msp/client/tls-ca/rca-juice-tls-cert.pem
      - PEER_CACERT=/etc/hyperledger/msp/users/peer0/msp/cacerts/rca-juice-blockchain-biz-8005.pem
      - ADMIN_SIGNCERTS=/etc/hyperledger/msp/users/admin/msp/signcerts/cert.pem
    working_dir: /etc/hyperledger/fabric
    volumes:
      # VM docker stream folder mapping
      - /var/run/:/host/var/run/
      # Default root path
      - ./peer0:/etc/hyperledger/fabric
      # Map the folder to root of Fabric CA crypto assets
      - ./rca:/etc/hyperledger/msp/
      # Folder with block channel config and tx file
      - ../config:/etc/hyperledger/config
      - ../channel:/etc/hyperledger/channel
      # For chaincode and application
      - ../application:/etc/hyperledger/application
      - ../chaincode:/etc/hyperledger/chaincode
    networks:
      - juice.net
    depends_on:
      - juice.peer0
    command: /bin/bash

# ==================================================================

  juice.peer1.couchdb:
    container_name: juice.peer1.couchdb
    image: hyperledger/fabric-couchdb:0.4.22
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admicouchdb1n Party" mode.
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=juice.blockchain
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_PEER_NETWORKID=juice.net
      - COUCHDB_USER=admin-db
      - COUCHDB_PASSWORD=admin-pwd
    working_dir: /etc/hyperledger/couchdb
    volumes:
      # VM docker stream folder mapping
      - /var/run:/host/var/run
      # Default root path
      - ./couchdb1:/etc/hyperledger/couchdb
    ports:
      # internal port changed to avoid conflict with other peer in other docker-compose.yml
      - 8232:5984
    networks:
      - juice.net

  juice.peer1:
    container_name: juice.peer1
    image: hyperledger/fabric-peer:1.4.9
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=juice.blockchain
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - CORE_PEER_FILESYSTEMPATH=/etc/hyperledger/fabric/ledger
      - CORE_PEER_NETWORKID=juice.net
      - CORE_PEER_ADDRESSAUTODETECT=false
      - CORE_PEER_ID=peer1.juice.blockchain.biz
      - CORE_PEER_LOCALMSPID=JuiceMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/peer1/msp
      - CORE_PEER_ADDRESS=peer1.juice.blockchain.biz:8234
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8234
      - CORE_PEER_ADMINSERVICE_LISTENADDRESS=0.0.0.0:8234
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8235
      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:8236
      # Go profiling tools only in none production environment
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_COMMITTER_ENABLED=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/msp/users/peer1/tls-msp/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/msp/users/peer1/tls-msp/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/users/peer1/tls-msp/tlscacerts/tls-rca-tlsring-blockchain-biz-5005.pem
      # - CORE_PEER_CHAINCODE_MODE=dev
      # - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.juice.blockchain.biz:8234
      - CORE_PEER_GOSSIP_ENDPOINT=peer1.juice.blockchain.biz:8234
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.juice.blockchain.biz:8234
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      # Logging
      - FABRIC_LOGGING_SPEC=info:ledger,peer,couchdb=info
      # - CORE_LOGGING_LEVEL=info:ledger,peer,couchdb=info
      # - CORE_LOGGING_COUCHDB=info
      # - CORE_LOGGING_CAUTHDSL=info
      # - CORE_LOGGING_GOSSIP=info
      # - CORE_LOGGING_GRPC=info
      # - CORE_LOGGING_KVLEDGER=info
      # - CORE_LOGGING_LEDGER=info
      # - CORE_LOGGING_MSP=info
      # - CORE_LOGGING_PEER=info
      # - CORE_LOGGING_POLICIES=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_CHAINCODE_LOGGING_SHIM=info
      - GRPC_GO_LOG_VERBOSITY_LEVEL=99
      - GRPC_GO_LOG_SEVERITY_LEVEL=info
      # Operations
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:8245
      - CORE_METRICS_PROVIDER=prometheus
      # For each historic key update, the historic value and associated transaction id and timestamp 
      # are stored in history database. See Class: ChaincodeStub and method <async> getHistoryForKey(key)
      - CORE_LEDGER_HISTORY_ENABLEHISTORYDATABASE=true
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=juice.peer1.couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin-db
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=admin-pwd
      # Additional PEER vars to support configs at runtime
      - TLSR_TLS_CERT=/etc/hyperledger/msp/client/tls-ca/rca-tlsring-tls-cert.pem
      - RCA_TLS_CERT=/etc/hyperledger/msp/client/tls-ca/rca-juice-tls-cert.pem
      - PEER_CACERT=/etc/hyperledger/msp/users/peer1/msp/cacerts/rca-juice-blockchain-biz-8005.pem
      - ADMIN_SIGNCERTS=/etc/hyperledger/msp/users/admin/msp/signcerts/cert.pem
    working_dir: /etc/hyperledger/fabric
    volumes:
      # VM docker stream folder mapping
      - /var/run/:/host/var/run/
      # Default root path
      - ./peer1:/etc/hyperledger/fabric
      # Map the folder to root of Fabric CA crypto assets
      - ./rca:/etc/hyperledger/msp/
      # Folder with block channel config and tx file
      - ../config:/etc/hyperledger/config
      - ../channel:/etc/hyperledger/channel
      # For chaincode and application
      - ../application:/etc/hyperledger/application
      - ../chaincode:/etc/hyperledger/chaincode
    ports:
      - 8234:8234
      - 8235:8235
      - 8236:8236
      - 8245:8245
    networks:
      - juice.net
    depends_on:
      - juice.peer1.couchdb
    command: peer node start
    # command: peer node start --peer-chaincodedev=true

  juice.peer1.cli:
    container_name: juice.peer1.cli
    image: hyperledger/fabric-tools:2.3.2
    tty: true
    stdin_open: true
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=juice.blockchain
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - CORE_PEER_FILESYSTEMPATH=/etc/hyperledger/fabric/ledger
      - FABRIC_LOGGING_SPEC=info
      - CORE_PEER_NETWORKID=juice.net
      - CORE_PEER_ADDRESSAUTODETECT=false
      - CORE_PEER_ID=peer1.juice.blockchain.biz
      - CORE_PEER_LOCALMSPID=JuiceMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/admin/msp
      - CORE_PEER_ADDRESS=peer1.juice.blockchain.biz:8234
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/msp/users/peer1/tls-msp/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/msp/users/peer1/tls-msp/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/users/peer1/tls-msp/tlscacerts/tls-rca-tlsring-blockchain-biz-5005.pem
      # Logging
      - FABRIC_LOGGING_SPEC=debug:ledger,peer,couchdb=debug
      # - CORE_LOGGING_LEVEL=info:ledger,peer,couchdb=info
      # - CORE_LOGGING_COUCHDB=info
      # - CORE_LOGGING_CAUTHDSL=info
      # - CORE_LOGGING_GOSSIP=info
      # - CORE_LOGGING_GRPC=info
      # - CORE_LOGGING_KVLEDGER=info
      # - CORE_LOGGING_LEDGER=info
      # - CORE_LOGGING_MSP=info
      # - CORE_LOGGING_PEER=info
      # - CORE_LOGGING_POLICIES=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_CHAINCODE_LOGGING_SHIM=info
      - GRPC_GO_LOG_VERBOSITY_LEVEL=99
      - GRPC_GO_LOG_SEVERITY_LEVEL=info
      # Additional PEER vars to support configs at runtime
      - TLSR_TLS_CERT=/etc/hyperledger/msp/client/tls-ca/rca-tlsring-tls-cert.pem
      - RCA_TLS_CERT=/etc/hyperledger/msp/client/tls-ca/rca-juice-tls-cert.pem
      - PEER_CACERT=/etc/hyperledger/msp/users/peer1/msp/cacerts/rca-juice-blockchain-biz-8005.pem
      - ADMIN_SIGNCERTS=/etc/hyperledger/msp/users/admin/msp/signcerts/cert.pem
    working_dir: /etc/hyperledger/fabric
    volumes:
      # VM docker stream folder mapping
      - /var/run/:/host/var/run/
      # Default root path
      - ./peer1:/etc/hyperledger/fabric
      # Map the folder to root of Fabric CA crypto assets
      - ./rca:/etc/hyperledger/msp/
      # Folder with block channel config and tx file
      - ../config:/etc/hyperledger/config
      - ../channel:/etc/hyperledger/channel
      # For chaincode and application
      - ../application:/etc/hyperledger/application
      - ../chaincode:/etc/hyperledger/chaincode
    networks:
      - juice.net
    depends_on:
      - juice.peer1
    command: /bin/bash

# ==================================================================
