NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/rca-corplisboa-blockchain-biz-8005.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/rca-corplisboa-blockchain-biz-8005.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/rca-corplisboa-blockchain-biz-8005.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/rca-corplisboa-blockchain-biz-8005.pem
    OrganizationalUnitIdentifier: orderer
