# ----------
# SPDX-License-Identifier: Apache-2.0
# ----------
#
---
################################################################################
#   Section: Organizations
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
################################################################################
Organizations: 

    - &CorpMaputo
        # Defines the organization which is used in the config 
        # of the fabric.git development environment
        Name: CorpMaputoMSP

        # ID to load the MSP definition as
        ID: CorpMaputoMSP

        MSPDir: ./rca/users/peer1/msp

        # Policies defines the set of policies at this level of the config tree
        # For organization policies, their canonical path is usually
        #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
        Policies: 
            Readers:
                Type: Signature
                Rule: "OR('CorpMaputoMSP.admin','CorpMaputoMSP.member','CorpMaputoMSP.peer','CorpMaputoMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('CorpMaputoMSP.admin','CorpMaputoMSP.member','CorpMaputoMSP.peer','CorpMaputoMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('CorpMaputoMSP.admin','CorpMaputoMSP.peer')"

        # OrdererEndpoints is a list of all orderers this org runs which clients
        # and peers may to connect to to push transactions and receive blocks respectively.
        # OrdererEndpoints:
        #     - "orderer.blockchain.biz:7050"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer1.corpmaputo.blockchain.biz
              Port: 9134

# END