# ----------
# SPDX-License-Identifier: Apache-2.0
# ----------
#
version: '3.5'

# volumes:
#   corptrading.orderer1:
#   corptrading.orderer2:
#   # corptrading.orderer3:
#   # corptrading.orderer4:

networks:
  corptrading.net:
    name: corptrading.blockchain

services:

  corptrading.rca:
    container_name: corptrading.rca
    image: hyperledger/fabric-ca:1.4.9
    environment:
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca/server
      - FABRIC_CA_SERVER_PORT=6005
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_NAME=rca.corptrading.blockchain.biz
      - FABRIC_CA_SERVER_CSR_CN=corptrading.blockchain.biz
      - FABRIC_CA_SERVER_CSR_HOSTS=rca.corptrading.blockchain.biz
      - FABRIC_CA_SERVER_DEBUG=true
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:6045
      - FABRIC_CA_SERVER_METRICS_PROVIDER=prometheus
    working_dir: /etc/hyperledger/fabric-ca/server 
    volumes:
      # VM docker stream folder mapping
      - /var/run/:/host/var/run/
      # Map the folder to root of Fabric CA crypto assets
      - ./rca:/etc/hyperledger/fabric-ca
    networks:
      - corptrading.net
    ports:
      - 6005:6005
      - 6045:6045
    command: sh -c 'fabric-ca-server start -d -b rcaCorpMaputo-admin:rca-pwd --port 6005'

# ==================================================================

  corptrading.orderer1:
    container_name: corptrading.orderer1
    image: hyperledger/fabric-orderer:1.4.9
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=corptrading.net
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - FABRIC_LOGGING_SPEC=info
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - ORDERER_HOME=/etc/hyperledger/fabric
      - ORDERER_FILELEDGER_LOCATION=/etc/hyperledger/fabric/production
      - ORDERER_GENERAL_LOGLEVEL=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=6950
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISPROFILE=MultiOrgOrdererEtcdRaft
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=CorpTradingMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/users/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/msp/users/orderer/tls-msp/signcerts/cert.pem
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/msp/users/orderer/tls-msp/keystore/key.pem
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/msp/users/orderer/tls-msp/tlscacerts/tls-ca-tlsrcontrol-blockchain-biz-5005.pem]
      - ORDERER_GENERAL_TLS_CLIENTAUTHREQUIRED=false
      - GODEBUG=netdns=go
      # Operations
      - ORDERER_GENERAL_OPERATIONS_LISTENADDRESS=0.0.0.0:6945
      - ORDERER_GENERAL_METRICS_PROVIDER=prometheus
      - ORDERER_DEBUG_BROADCASTTRACEDIR=data/logs
      # Additional ORDERER vars to support configs at runtime
      - TLSR_TLS_CERT=/etc/hyperledger/msp/client/tls-ca/ca-tlsrcontrol-tls-cert.pem
      - RCA_TLS_CERT=/etc/hyperledger/msp/client/tls-ca/rca-corptrading-tls-cert.pem
      - ORDERER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/client/tls-root-cert/rca-corptrading-ca-cert.pem
      - ORDERER_CACERT=/etc/hyperledger/msp/users/orderer/msp/cacerts/rca-corptrading-blockchain-biz-6005.pem
      - ADMIN_ORDERER_CACERT=/etc/hyperledger/msp/users/admin/msp/cacerts/rca-corptrading-blockchain-biz-6005.pem
      # Ordering CLuster
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/etc/hyperledger/msp/users/orderer/tls-msp/signcerts/cert.pem
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/etc/hyperledger/msp/users/orderer/tls-msp/keystore/key.pem
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/etc/hyperledger/msp/users/orderer/tls-msp/tlscacerts/tls-ca-tlsrcontrol-blockchain-biz-5005.pem]
      - ORDERER_FILELEDGER_PREFIX=hlf-orderer1-corptrading
      - ORDERER_HOST=orderer1.corptrading.blockchain.biz
    working_dir: /etc/hyperledger/fabric
    volumes:
      # VM docker stream folder mapping
      - /var/run/:/host/var/run/
      # Default root path
      - ./orderer1:/etc/hyperledger/fabric
      # Map the folder to root of Fabric CA crypto assets
      - ./rca/client:/etc/hyperledger/msp/client
      - ./rca/users/admin:/etc/hyperledger/msp/users/admin
      - ./rca/users/orderer1:/etc/hyperledger/msp/users/orderer
      # Folder with channel create tx file
      - ../configtx:/etc/hyperledger/configtx
      # For chaincode and application
      - ../application:/etc/hyperledger/application
      - ../chaincode:/etc/hyperledger/chaincode
    ports:
      - 6130:6950
      - 6145:6945
    networks:
      - corptrading.net
    command: orderer

  corptrading.orderer2:
    container_name: corptrading.orderer2
    image: hyperledger/fabric-orderer:1.4.9
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=corptrading.net
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - FABRIC_LOGGING_SPEC=info
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - ORDERER_HOME=/etc/hyperledger/fabric
      - ORDERER_FILELEDGER_LOCATION=/etc/hyperledger/fabric/production
      - ORDERER_GENERAL_LOGLEVEL=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=6950
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISPROFILE=MultiOrgOrdererEtcdRaft
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=CorpTradingMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/users/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/msp/users/orderer/tls-msp/signcerts/cert.pem
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/msp/users/orderer/tls-msp/keystore/key.pem
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/msp/users/orderer/tls-msp/tlscacerts/tls-ca-tlsrcontrol-blockchain-biz-5005.pem]
      - ORDERER_GENERAL_TLS_CLIENTAUTHREQUIRED=false
      - GODEBUG=netdns=go
      # Operations
      - ORDERER_GENERAL_OPERATIONS_LISTENADDRESS=0.0.0.0:6945
      - ORDERER_GENERAL_METRICS_PROVIDER=prometheus
      - ORDERER_DEBUG_BROADCASTTRACEDIR=data/logs
      # Additional ORDERER vars to support configs at runtime
      - TLSR_TLS_CERT=/etc/hyperledger/msp/client/tls-ca/ca-tlsrcontrol-tls-cert.pem
      - RCA_TLS_CERT=/etc/hyperledger/msp/client/tls-ca/rca-corptrading-tls-cert.pem
      - ORDERER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/client/tls-root-cert/rca-corptrading-ca-cert.pem
      - ORDERER_CACERT=/etc/hyperledger/msp/users/orderer/msp/cacerts/rca-corptrading-blockchain-biz-6005.pem
      - ADMIN_ORDERER_CACERT=/etc/hyperledger/msp/users/admin/msp/cacerts/rca-corptrading-blockchain-biz-6005.pem
      # Ordering CLuster
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/etc/hyperledger/msp/users/orderer/tls-msp/signcerts/cert.pem
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/etc/hyperledger/msp/users/orderer/tls-msp/keystore/key.pem
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/etc/hyperledger/msp/users/orderer/tls-msp/tlscacerts/tls-ca-tlsrcontrol-blockchain-biz-5005.pem]
      - ORDERER_FILELEDGER_PREFIX=hlf-orderer2-corptrading
      - ORDERER_HOST=orderer2.corptrading.blockchain.biz
    working_dir: /etc/hyperledger/fabric
    volumes:
      # VM docker stream folder mapping
      - /var/run/:/host/var/run/
      # Default root path
      - ./orderer2:/etc/hyperledger/fabric
      # Map the folder to root of Fabric CA crypto assets
      - ./rca/client:/etc/hyperledger/msp/client
      - ./rca/users/admin:/etc/hyperledger/msp/users/admin
      - ./rca/users/orderer2:/etc/hyperledger/msp/users/orderer
      # Folder with channel create tx file
      - ../configtx:/etc/hyperledger/configtx
      # For chaincode and application
      - ../application:/etc/hyperledger/application
      - ../chaincode:/etc/hyperledger/chaincode
    ports:
      - 6230:6950
      - 6245:6945
    networks:
      - corptrading.net
    command: orderer    

  corptrading.orderer3:
    container_name: corptrading.orderer3
    image: hyperledger/fabric-orderer:1.4.9
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=corptrading.net
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - FABRIC_LOGGING_SPEC=info
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - ORDERER_HOME=/etc/hyperledger/fabric
      - ORDERER_FILELEDGER_LOCATION=/etc/hyperledger/fabric/production
      - ORDERER_GENERAL_LOGLEVEL=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=6950
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISPROFILE=MultiOrgOrdererEtcdRaft
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=CorpTradingMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/users/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/msp/users/orderer/tls-msp/signcerts/cert.pem
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/msp/users/orderer/tls-msp/keystore/key.pem
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/msp/users/orderer/tls-msp/tlscacerts/tls-ca-tlsrcontrol-blockchain-biz-5005.pem]
      - ORDERER_GENERAL_TLS_CLIENTAUTHREQUIRED=false
      - GODEBUG=netdns=go
      # Operations
      - ORDERER_GENERAL_OPERATIONS_LISTENADDRESS=0.0.0.0:6945
      - ORDERER_GENERAL_METRICS_PROVIDER=prometheus
      - ORDERER_DEBUG_BROADCASTTRACEDIR=data/logs
      # Additional ORDERER vars to support configs at runtime
      - TLSR_TLS_CERT=/etc/hyperledger/msp/client/tls-ca/ca-tlsrcontrol-tls-cert.pem
      - RCA_TLS_CERT=/etc/hyperledger/msp/client/tls-ca/rca-corptrading-tls-cert.pem
      - ORDERER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/client/tls-root-cert/rca-corptrading-ca-cert.pem
      - ORDERER_CACERT=/etc/hyperledger/msp/users/orderer/msp/cacerts/rca-corptrading-blockchain-biz-6005.pem
      - ADMIN_ORDERER_CACERT=/etc/hyperledger/msp/users/admin/msp/cacerts/rca-corptrading-blockchain-biz-6005.pem
      # Ordering CLuster
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/etc/hyperledger/msp/users/orderer/tls-msp/signcerts/cert.pem
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/etc/hyperledger/msp/users/orderer/tls-msp/keystore/key.pem
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/etc/hyperledger/msp/users/orderer/tls-msp/tlscacerts/tls-ca-tlsrcontrol-blockchain-biz-5005.pem]
      - ORDERER_FILELEDGER_PREFIX=hlf-orderer3-corptrading
      - ORDERER_HOST=orderer3.corptrading.blockchain.biz
    working_dir: /etc/hyperledger/fabric
    volumes:
      # VM docker stream folder mapping
      - /var/run/:/host/var/run/
      # Default root path
      - ./orderer3:/etc/hyperledger/fabric
      # Map the folder to root of Fabric CA crypto assets
      - ./rca/client:/etc/hyperledger/msp/client
      - ./rca/users/admin:/etc/hyperledger/msp/users/admin
      - ./rca/users/orderer3:/etc/hyperledger/msp/users/orderer
      # Folder with channel create tx file
      - ../configtx:/etc/hyperledger/configtx
      # For chaincode and application
      - ../application:/etc/hyperledger/application
      - ../chaincode:/etc/hyperledger/chaincode
    ports:
      - 6330:6950
      - 6345:6945
    networks:
      - corptrading.net
    command: orderer

# End